workflows:
  ios-workflow:
    name: Zyiarah iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter Packages
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Setup Code Signing
        script: |
          export CM_CERTIFICATE="$(base64 -i ios/zyiarah_dist_cert.p12 | tr -d '\n')"
          export CM_CERTIFICATE_PASSWORD="uZiESgq5"
          export CM_PROVISIONING_PROFILE="$(base64 -i ios/Zyiarah_App_Store_Profile.mobileprovision | tr -d '\n')"
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles
      - name: Force Xcode Distribution
        script: |
          echo "CODE_SIGN_IDENTITY=Apple Distribution" >> ios/Flutter/Release.xcconfig
          echo "PROVISIONING_PROFILE_SPECIFIER=" >> ios/Flutter/Release.xcconfig
      - name: iOS Build
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - support@zyiarah.com
        notify:
          success: true
          failure: false
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

