// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwyG5_yH1rKd-CBQGwQylw2n8jrPbn17o',
    appId: '1:275681992607:web:6dc4a0042fab5b69b127aa',
    messagingSenderId: '275681992607',
    projectId: 'zyiarah-app',
    authDomain: 'zyiarah-app.firebaseapp.com',
    storageBucket: 'zyiarah-app.firebasestorage.app',
    measurementId: 'G-K82D1GDJNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbbW7MmqVa4nPyxLURj1bj9DAAYE_U4GI',
    appId: '1:275681992607:android:369f833ebbd0a9f7b127aa',
    messagingSenderId: '275681992607',
    projectId: 'zyiarah-app',
    storageBucket: 'zyiarah-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmlXZaIvQpMful2kK3EgGD7B3JFman1I',
    appId: '1:275681992607:ios:46ef8f0f245398f7b127aa',
    messagingSenderId: '275681992607',
    projectId: 'zyiarah-app',
    storageBucket: 'zyiarah-app.firebasestorage.app',
    iosBundleId: 'com.zyiarah.zyiarah',
  );
}
